# Generated by Django 5.1.15 on 2026-08-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('paper_date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=1024)),
                ('source_uuid', models.CharField(max_length=64, unique=True)),
                ('source_paper_id', models.CharField(blank=True, max_length=128)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='acts.act')),
            ],
            options={
                'ordering': ['-paper_date'],
            },
        ),
    ]
