# Generated by Django 5.1.15 on 2026-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_actpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actpaper',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
